[config]

[templates.niri-focus]
input_path = "~/.config/matugen/templates/niri-focus.kdl"
output_path = "~/.cache/DankMaterialShell/niri-focus.kdl"

[templates.fastfetch]
input_path = "~/.config/matugen/templates/fastfetch.jsonc"
output_path = "~/.cache/matugen/fastfetch.jsonc"

[templates.starship]
input_path = "~/.config/matugen/templates/starship.toml"
output_path = "~/.cache/matugen/starship.toml"
