# Preset from:
# https://starship.rs/presets/pastel-powerline
"$schema" = 'https://starship.rs/config-schema.json'
palette = "matugen"
format = """
[](color5)\
$username\
[](fg:color5 bg:color6)\
$directory\
[](fg:color6 bg:color12)\
$git_branch\
$git_status\
[](fg:color12 bg:color6)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$maven\
$nodejs\
$bun\
$nim\
$rust\
$scala\
[](fg:color6 bg:color13)\
$docker_context\
[](fg:color13 bg:color15)\
$time\
[ ](fg:color15)\
"""
# Disable the blank line at the start of the prompt
# add_newline = false
[username]
show_always = true
style_user = "fg:color7 bg:color5"
style_root = "fg:color7 bg:color5"
format = '[₊˚⊹♡ ᓚ₍ ^. .^₎  ]($style)'
disabled = false
[os]
style = "fg:color7 bg:color5"
disabled = true
[directory]
style = "fg:color5 bg:color6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"~" = " "
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
[c]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[cpp]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[docker_context]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol $context ]($style)'
[elixir]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[elm]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[git_branch]
symbol = ""
style = "fg:color7 bg:color12"
format = '[ $symbol $branch ]($style)'
[git_status]
style = "fg:color7 bg:color12"
format = '[$all_status$ahead_behind ]($style)'
[golang]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[gradle]
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[haskell]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[java]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[julia]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[maven]
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[nodejs]
symbol = ""
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[bun]
symbol = ""
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[nim]
symbol = "󰆥 "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[rust]
symbol = ""
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[scala]
symbol = " "
style = "fg:color5 bg:color6"
format = '[ $symbol ($version) ]($style)'
[time]
disabled = false
time_format = "%R"
style = "fg:color5 bg:color15"
format = '[ 󰣐 $time ]($style)'
# ── Colors ───────────────────────────────────────────────────────────────────
[palettes.matugen]
color0  = "{{colors.background.default}}"
color1  = "{{colors.error.default}}"
color2  = "{{colors.tertiary.default}}"
color3  = "{{colors.secondary_container.default}}"
color4  = "{{colors.tertiary_container.default}}"
color5  = "{{colors.primary.default}}"
color6  = "{{colors.primary_container.default}}"
color7  = "{{colors.on_primary_container.default}}"
color8  = "{{colors.outline.default}}"
color9  = "{{colors.error_container.default}}"
color10 = "{{colors.on_tertiary.default}}"
color11 = "{{colors.on_secondary_container.default}}"
color12 = "{{colors.on_tertiary_container.default}}"
color13 = "{{colors.secondary.default}}"
color14 = "{{colors.on_secondary.default}}"
color15 = "{{colors.on_primary.default}}"
